"""Update feedback table structure

Revision ID: 04b7045a074a
Revises: e8386db0c293
Create Date: 2024-07-30 15:17:00.662261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b7045a074a'
down_revision = 'e8386db0c293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('weather',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('weather',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.Text(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
