"""Change timestamp to string

Revision ID: f2409976294b
Revises: 04b7045a074a
Create Date: 2024-07-30 15:29:40.657956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2409976294b'
down_revision = '04b7045a074a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=19),
               existing_nullable=False)
        batch_op.alter_column('weather',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.alter_column('weather',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=19),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
